#! /bin/bash

beispiel=ag
allow_null_glob_expansion=1
shopt -s nullglob
PROGRAM=./$beispiel
errnum=0
prgnum=0

LOC=/home/maximilian/Projects/CompilerConstruction/test/$beispiel
LOC2=/home/maximilian/Projects/CompilerConstruction/test/$beispiel/cases

if [ ! -d /home/maximilian/Projects/CompilerConstruction/$beispiel ]; then
  echo "[Error] directory ~/abgabe/$beispiel does not exist."
  exit 1
else
  cd /home/maximilian/Projects/CompilerConstruction/$beispiel
  echo 'Testing "make clean"'
  make clean
  /home/maximilian/Projects/CompilerConstruction/test/cleantest
  echo 'Testing "make"'
  make
fi

if test ! -x $PROGRAM
then
  echo "[Error] executable $PROGRAM not generated! ('make')"
  exit 1
fi
for i in $LOC/*.[0123] $LOC2/*.[0123]
do
        echo "---------------------------------------------------------------------"
	echo "Test file: $i"
        echo "Input:"
        echo "======"
        echo
        cat $i
        echo
        let prgnum=prgnum+1
	$PROGRAM <$i >/dev/null 2>/dev/null
	retval=$?
	if test $retval -eq ${i##*.}
	then
		echo "Correct exit status."
	else
                echo "[Error] Status is $retval but ${i##*.} was expected!"
                echo   
                let errnum=errnum+1   
	fi
done
echo "---------------------------------------------------------------------"
echo
let corrnum=prgnum-errnum
echo "Statistics: "
echo "==========="
echo "           $prgnum Tests total"
echo "           $corrnum Tests passed"
echo "           $errnum Tests failed"
