#!/bin/bash

beispiel=parser
allow_null_glob_expansion=1
shopt -s nullglob
PROGRAM=./$beispiel
errnum=0
prgnum=0

LOC=/usr/ftp/pub/ublu/test/$beispiel
LOC2=~/test/$beispiel

/usr/ftp/pub/ublu/test/accounttest || exit 1
if [ ! -d ~/abgabe/$beispiel ]; then
  echo "[Error] directory ~/abgabe/$beispiel does not exist."
  exit 1
else
  cd ~/abgabe/$beispiel
  echo 'Testing "make clean"'
  make clean
  /usr/ftp/pub/ublu/test/cleantest
  echo 'Testing "make"'
  make
fi

if test ! -x $PROGRAM
then
  echo "[Error] executable $PROGRAM not generated! ('make')"
  exit 1
fi
for i in $LOC/*.[012] $LOC2/*.[012]
do
        echo "---------------------------------------------------------------------"
	echo "Test file: $i"
        echo "Input:"
        echo "======"
        echo
        cat $i
        echo
        let prgnum=prgnum+1
	$PROGRAM <$i >/dev/null 2>/dev/null
	retval=$?
	if test $retval -eq ${i##*.}
	then
		echo "Correct exit status."
	else
                echo "[Error] Status is $retval but ${i##*.} was expected!"
                echo   
                let errnum=errnum+1   
	fi
done
echo "---------------------------------------------------------------------"
echo
let corrnum=prgnum-errnum
echo "Statistics:"
echo "==========="
echo "           $prgnum Tests total"
echo "           $corrnum Tests passed"
echo "           $errnum Tests failed"
