#! /bin/bash

beispiel=codeb
PROGRAM=./$beispiel

errnum=0
prgnum=0

#LOC=.
LOC=/home/maximilian/Projects/CompilerConstruction/test/$beispiel
LOC2=/home/maximilian/Projects/CompilerConstruction/test/$beispiel/cases

# colors
RED_COLOR='\033[0;31m'
GREEN_COLOR='\033[0;32m'
PURPLE_COLOR='\033[0;35m'
NO_COLOR='\033[0m'

allow_null_glob_expansion=1

if [ ! -d /home/maximilian/Projects/CompilerConstruction/$beispiel ]; then
  echo "Fehler: Verzeichnis ~/abgabe/$beispiel existiert nicht."
  exit 1
else
  cd /home/maximilian/Projects/CompilerConstruction/$beispiel
  echo 'Teste "make clean"'
  make clean
  /home/maximilian/Projects/CompilerConstruction/test/cleantest
  echo 'Teste "make"'
  make
fi

if test ! -x $PROGRAM
then
	echo "Fehler: Kein Programm $PROGRAM"
	exit 1
fi
let prgnum=0
for i in $LOC/*.0 $LOC2/*.0 $LOC/*.xin $LOC2/*.xin
do
	if [ -f $i ]; then
	    let prgnum=prgnum+1
	    let errorfound=0
	    echo "==========> Eingabe von $i:"
	    cat $i
	    echo
	    RESFILE=test${beispiel}out$$
	    $PROGRAM <$i >$RESFILE
	    retval=$?
	    echo -n "Übersetzung: "
	    if test $retval -eq 0
	    then
		    echo "Status korrekt"
		    echo -e "${GREEN_COLOR}----------------------------------------------------------------------------------TEST PASSED${NO_COLOR}"
	    else
		    echo "[Errot] Status=$retval. Erwartet: 0"
		    echo -e "${RED_COLOR}----------------------------------------------------------------------------------TEST FAILED${NO_COLOR}"
		    let errorfound=1
	    fi
	    echo
	    echo "Ausgabe:"
	    cat $RESFILE
	    mv -f $RESFILE $RESFILE.s
	    CALLFILE=${i%.*}.call
	    echo
	    if [ ! -f $CALLFILE ]; then
		echo "Fehler: Datei $CALLFILE existiert nicht, kann Code nicht ausführen..."
		exit 1
	    else
		echo "Übersetze und linke das Testprogramm:"
		if cc -fno-pie -no-pie -g -I. -DCALL=\"$CALLFILE\" $LOC/testmain.c $LOC/callingconvention.o $RESFILE.s; then
		    echo
		    echo "Rufe folgendes Codefragment auf:"
		    cat $CALLFILE
		    echo
		    ./a.out
		    retval=$?
		    # test callee saved registers
		    if [ "$retval" -ge 12 ] && [ "$retval" -le 15 ]; then
			echo "[Error] Callee-saved register %r$retval modified."
                        let errorfound=1
		    elif [ "$retval" -eq 11 ]; then
			echo "[Error] Callee-saved register %rbx modified."
                        let errorfound=1
		    elif [ "$retval" -eq 16 ]; then
			echo "[Error] Callee-saved register %rbp modified."
                        let errorfound=1
		    elif [ "$retval" -eq 30 ]; then
			echo "[Error] Stack pointer %rsp modified."
                        let errorfound=1
                    else
                        # test signals
			test $retval -gt 127
			retsig=$?
			test ${i##*.} = xin
			expsig=$?
			if test $retsig -eq $expsig; then
                            echo "Erzeugter Code verhaelt sich bezueglich Signal-Erzeugung wie erwartet"
			    if test $retval -eq 1; then
				echo "[Error] aber das Ergebnis des Aufrufs ist falsch."
				echo -e "${RED_COLOR}----------------------------------------------------------------------------------TEST FAILED${NO_COLOR}"
				let errorfound=1
			    else
				echo "und das Ergebnis des Ausdrucks ist korrekt."
				echo -e "${GREEN_COLOR}----------------------------------------------------------------------------------TEST PASSED${NO_COLOR}"
			    fi
			else
			    echo "[Error] Erzeugter Code verhaelt sich bezueglich Signalerzeugung anders als erwartet."
			    let errorfound=1
			    echo "Rueckgabewert = $retval";
			    echo -e "${RED_COLOR}----------------------------------------------------------------------------------TEST FAILED${NO_COLOR}"
			fi
		    fi
		    echo
		else
		    echo "[Error] Erzeugter Code konnte nicht assembliert und gelinkt werden."
        echo -e "${RED_COLOR}----------------------------------------------------------------------------------TEST FAILED${NO_COLOR}"
		    let errorfound=1
		fi
	    fi
	    let errnum=errnum+errorfound
	    rm -f a.out $RESFILE $RESFILE.s
	fi
done

for i in $LOC/*.[123] $LOC2/*.[123]
do
	if [ -f $i ]; then
	let prgnum=prgnum+1
	echo "==========> Eingabe von $i:"
	cat $i
	echo
	echo "Ausgabe:"
	$PROGRAM <$i
	retval=$?
	if test $retval -eq ${i#*.}
	then
		echo "Status: korrekt"
		echo -e "${GREEN_COLOR}----------------------------------------------------------------------------------TEST PASSED${NO_COLOR}"
	else
		echo "[Error] Status: $retval. Erwartet: ${i#*.}"
		echo -e "${RED_COLOR}----------------------------------------------------------------------------------TEST FAILED${NO_COLOR}"
		let errnum=errnum+1
	fi
	echo
fi
done
let corrnum=prgnum-errnum
echo "Statistics: "
echo "==========="
echo "           $prgnum Tests total"
echo "           $corrnum Tests passed"
echo "           $errnum Tests failed"


make clean