#! /bin/bash

beispiel=scanner
allow_null_glob_expansion=1
shopt -s nullglob
PROGRAM=./$beispiel
errnum=0
prgnum=0

LOC=/usr/ftp/pub/ublu/test/$beispiel
LOC2=~/test/$beispiel

/usr/ftp/pub/ublu/test/accounttest || exit 1
if [ ! -d ~/abgabe/$beispiel ]; then
  echo "[Error] directory ~/abgabe/$beispiel does not exist."
  exit 1
else
  cd ~/abgabe/$beispiel
  echo 'Testing "make clean"'
  make clean
  /usr/ftp/pub/ublu/test/cleantest
  echo 'Testing "make"'
  make
fi
  
if test ! -x $PROGRAM
then
  echo "[Error] executable $PROGRAM not generated! ('make')"
  exit 1
fi
for i in $LOC/*.0 $LOC2/*.0
do
    echo "---------------------------------------------------------------------"
    echo "Test file: $i"
    echo "Input:"
    echo "======"
    cat $i
    echo
    let prgnum=prgnum+1
    $PROGRAM <$i >/dev/null
    retval=$?
    if test $retval -eq 0
    then
	OUTFILE=`dirname $i`/`basename $i .0`.out
	($PROGRAM <$i | diff -w -c -s - $OUTFILE) >/dev/null
	retval=$?
	if test $retval -eq 0
	then
	    echo "Correct output."
        else
	    echo "[Error] incorrect output"
	    let errnum=errnum+1   
	    echo   
	    echo "Expected output:"
	    echo "================"
	    cat $OUTFILE
	    echo 
	    echo "Difference:"
	    echo "==========="
	    $PROGRAM <$i | diff -w -c -s - $OUTFILE
            echo
	fi
	else
	    echo "[Error] Status is $retval but 0 was expected!"
            echo   
            let errnum=errnum+1   
	fi
done
for i in $LOC/*.1 $LOC2/*.1
do
        echo "---------------------------------------------------------------------"
	echo "Test file: $i"
        let prgnum=prgnum+1
        echo
	$PROGRAM <$i >/dev/null
	retval=$?
	if test $retval -eq 1
	then
		echo "Correct output."
	else
                echo "Input:"
                echo "======"
                cat $i
                echo
		echo "[Error] Status is $retval but 1 was expected!"
                echo
                let errnum=errnum+1   
	fi
done
echo "---------------------------------------------------------------------"
echo
let corrnum=prgnum-errnum
echo "Statistics:"
echo "==========="
echo "           $prgnum Tests total"
echo "           $corrnum Tests passed"
echo "           $errnum Tests failed"














